# Theme settings
doks:
    baseurl: 
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: YouTrackDB
            image:
        nav:
    footer:
        content:
            logo:
                text: YouTrackDB
                image:
            copyright: Copyright &copy; JetBrains s.r.o. 2025 - YouTrackDB <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/youtrackdb/youtrackdb'
    google_analytics:
        tracking_code: G-PV9W92HTXL
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    style: compressed

# Jekyll settings
layouts_dir: doks-theme/_layouts
includes_dir: doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
